# _____________________________ languages.py _____________________________

languages = {
    'persian': {
        'app_title': 'برنامه ساخت جلد',
        'theme_button': '🎨 تم ها',
        'history_button': 'تاریخچه',
        'guide_button': ' راهنما',
        'language': 'زبان',
        "erorr": "خطا",
        'about_button': '📋 درباره ما',
        'about_title': 'درباره برنامه',
        'about_message': '''📱 برنامه ساخت جلد

توسعه دهندگان : آقایان مقیسه و شاکر

📅 نسخه: {}
📧 پشتیبانی: support@example.com
📞 تلفن: ۰۲۱-۱۲۳۴۵۶۷۸

⭐ این برنامه برای ساخت انواع جلد طراحی شده است.
❤️ با تشکر از انتخاب شما''',
        'other_programs': '📦 برنامه‌های دیگر',
        'other_programs_title': 'سایر برنامه‌های من',
        'loading_repos': 'در حال بارگذاری اطلاعات...',
        'github_error': 'خطا در ارتباط با گیت‌هاب',
        'no_other_programs': 'هیچ برنامه دیگری یافت نشد',
        'view_on_github': 'مشاهده در گیت‌هاب',
        'more_info': 'اطلاعات بیشتر',
        'refresh': 'بررسی مجدد',
        'description': 'توضیحات',
        'no_description': 'بدون توضیحات',
        'unknown': 'نامشخص',
        'language_colon': 'زبان',
        'stars': 'ستاره‌ها',
        'created_at': 'تاریخ ایجاد',
        'updated_at': 'آخرین به‌روزرسانی',
        'link': 'لینک',
        'update_title': 'بررسی به‌روزرسانی',
        'current_version_checking': 'نسخه فعلی: در حال بررسی...',
        'latest_version_checking': 'آخرین نسخه: در حال بررسی...',
        'current_version': 'نسخه فعلی',
        'current_version_unknown': 'نسخه فعلی: نامشخص',
        'latest_version': 'آخرین نسخه',
        'check_update': 'بررسی به‌روزرسانی',
        'check_again': 'بررسی مجدد',
        'start_update': 'شروع به‌روزرسانی',
        'checking': 'در حال بررسی...',
        'connecting_github': 'در حال ارتباط با گیت‌هاب...',
        'github_connection_error': 'خطا در ارتباط با گیت‌هاب',
        'app_up_to_date': 'برنامه شما به‌روز است',
        'new_version_available': 'نسخه جدید {} موجود است',
        'new_version_found': 'نسخه جدید',
        'update_question': 'آیا می‌خواهید به‌روزرسانی کنید؟',
        'update_note': 'توجه: فایل‌های .gitignore و README.md به‌روزرسانی نمی‌شوند.',
        'updating': 'در حال به‌روزرسانی...',
        'downloading_updating': 'در حال دانلود و به‌روزرسانی...',
        'update_successful': 'به‌روزرسانی با موفقیت انجام شد (نسخه {})',
        'update_successful_title': 'به‌روزرسانی موفق',
        'update_successful_message': 'برنامه با موفقیت به نسخه',
        'restart_question': 'برای اعمال تغییرات، برنامه باید مجدداً راه‌اندازی شود. آیا می‌خواهید اکنون راه‌اندازی مجدد شود؟',
        'restarting': 'در حال راه‌اندازی مجدد...',
        'update_error': 'خطا در به‌روزرسانی',
        'restart_error': 'خطا در راه‌اندازی مجدد',
        'update': 'به‌روزرسانی',
        'dissertation_cover': 'ساخت جلد\n پایان نامه',
        'notebook_cover': 'ساخت جلد\n  دفتر مدارس یا\n  قراردادها',
        'book_cover': 'ساخت جلد\n  کتاب ها',
        'gilded_book_cover': 'ساخت جلد\n  کتاب های \n  تذهیب دار',
        'theme_guide_title': 'راهنمای تنظیم تم برنامه',
        'theme_guide_message': 'یکی از رنگ ها را انتخاب کنید تا رنگ تمام دکمه های برنامه عوض شود',
        'background_color': 'رنگ پس زمینه',
        'history_guide_title': 'صفحه تاریخچه',
        'history_guide_message': 'در این صفحه می‌توانید آخرین فایل‌های ساخته شده را مشاهده کنید',
        'clear_all': '🧹 پاک کردن همه',
        'change_path': '📁 تغییر مسیر',
        'empty_history': '📭 تاریخچه خالی است',
        'delete_confirm': 'آیا از حذف این مورد مطمئن هستید؟',
        'clear_all_confirm': 'آیا از پاک کردن کامل تاریخچه مطمئن هستید؟',
        'delete_success': 'مورد با موفقیت حذف شد',
        'clear_all_success': 'تاریخچه با موفقیت پاک شد',
        'save_file': 'ذخیره فایل',
        'file_saved': 'فایل با موفقیت ذخیره شد',
        'file_saved_path': 'فایل در مسیر زیر ذخیره شد:',
        'info_title': 'اطلاعات فایل',
        'file_name': 'نام فایل',
        'creation_date': 'تاریخ ایجاد',
        'original_path': 'مسیر اصلی',
        'build_info': 'اطلاعات ساخت',
        'title': 'عنوان',
        'author': 'نویسنده',
        'spine_value_info': 'مقدار عطف',
        'page_number': 'شماره صفحه',
        'latin_page': 'صفحه لاتین',
        'has': 'دارد',
        'does_not_have': 'ندارد',
        'logo_type': 'نوع لوگو',
        'black_white': 'سیاه و سفید',
        'colored': 'رنگی',
        'logo_shape': 'شکل لوگو',
        'circular': 'دایره‌ای',
        'non_circular': 'غیر دایره‌ای',
        'mm': 'میلی‌متر',
        'step1': 'مرحله ۱',
        'step2': 'مرحله ۲',
        'step3': 'مرحله ۳',
        'step4': 'مرحله ۴',
        'help_plan_1': 'راهنمای مرحله اول',
        'help_plan_2': 'راهنمای مرحله دوم',
        'help_plan_3': 'راهنمای مرحله سوم',
        'help_plan_4': 'راهنمای مرحله چهارم',
        'spine_value': ':(mm)مقدار عطف ',
        'title_text': ':عنوان ',
        'author_name': ':نام نویسنده ',
        'date': ':تاریخ ',
        'title_page_number': ': شماره صفحه عنوان ',
        'output_file_name': ':نام فایل خروجی ',
        'select_file': 'انتخاب فایل ',
        'save_location': 'محل ذخیره ',
        'no_file_selected': 'فایلی انتخاب نشده است',
        'no_folder_selected': 'پوشه ای انتخاب نشده است',
        'no_logo_selected': 'لوگو انتخاب نشده است',
        'file_selected': 'فایل انتخاب شد',
        'folder_selected': 'پوشه انتخاب شد',
        'logo_selected': 'لوگو انتخاب شد',
        'start_making_message': 'فرآیند ساخت جلد آغاز شد...',
        'has_latin_page': 'پایان نامه صفحه لاتین دارد',
        'has_latin_page_on': 'دارای صفحه لاتین',
        'has_latin_page_off': 'بدون صفحه لاتین',
        'logo_black_white': 'لوگوی پایان نامه سیاه و سفید است',
        'logo_black_white_on': 'سیاه و سفید',
        'logo_black_white_off': 'رنگی',
        'logo_circular': 'لوگوی پایان نامه دایره ای است',
        'logo_circular_on': 'دایره ای',
        'logo_circular_off': 'غیر دایره ای',
        'refresh': 'پاکسازی صفحه',
        'start_making': 'شروع ساخت',
        'load_logo': 'بارگذاری لوگو',
        'back': '🔙 بازگشت',
        'cancel': 'انصراف',
        'apply': 'اعمال',
        'select_year': 'انتخاب سال',
        'select_month': 'انتخاب ماه',
        'selected_date': ':تاریخ انتخاب شده ',
        'months': ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور',
                   'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'],
        'pages': ['۱ صفحه', '۲ صفحه', '۳ صفحه', '۴ صفحه', '۵ صفحه'],
        'welcome_message': '''بسم الله الرحمن الرحیم
سلام به برنامه ساخت جلد خوش آمدید
برای ساخت هر نوع جلد روی کلید مربوطه کلیک نمائید''',
        'about_us': '''📱 برنامه ساخت جلد

توسعه دهندگان : آقایان مقیسه و شاکر

📅 نسخه: {}
📧 پشتیبانی: support@example.com
📞 تلفن: ۰۲۱-۱۲۳۴۵۶۷۸

⭐ این برنامه برای ساخت انواع جلد طراحی شده است.

❤️ با تشکر از انتخاب شما''',
    },
    
    'english': {
        'app_title': 'Cover Builder',
        'theme_button': '🎨 Themes',
        'history_button': 'History',
        'guide_button': ' Guide',
        'language': 'Language',
        "erorr": 'error',
        'about_button': '📋 About Us',
        'about_title': 'About App',
        'about_message': '''📱 Cover Builder

Developers: Moghiseh & Shaker

📅 Version: {}
📧 Support: support@example.com
📞 Phone: +98-21-12345678

⭐ Designed for creating various covers
❤️ Thank you for choosing us''',
        'other_programs': '📦 Other Programs',
        'other_programs_title': 'My Other Programs',
        'loading_repos': 'Loading information...',
        'github_error': 'Error connecting to GitHub',
        'no_other_programs': 'No other programs found',
        'view_on_github': 'View on GitHub',
        'more_info': 'More Info',
        'refresh': 'Refresh',
        'description': 'Description',
        'no_description': 'No description',
        'unknown': 'Unknown',
        'language_colon': 'Language',
        'stars': 'Stars',
        'created_at': 'Created at',
        'updated_at': 'Updated at',
        'link': 'Link',
        'update_title': 'Check for Updates',
        'current_version_checking': 'Current version: Checking...',
        'latest_version_checking': 'Latest version: Checking...',
        'current_version': 'Current version',
        'current_version_unknown': 'Current version: Unknown',
        'latest_version': 'Latest version',
        'check_update': 'Check for Updates',
        'check_again': 'Check Again',
        'start_update': 'Start Update',
        'checking': 'Checking...',
        'connecting_github': 'Connecting to GitHub...',
        'github_connection_error': 'Error connecting to GitHub',
        'app_up_to_date': 'Your app is up to date',
        'new_version_available': 'New version {} available',
        'new_version_found': 'New version',
        'update_question': 'Do you want to update?',
        'update_note': 'Note: .gitignore and README.md files will not be updated.',
        'updating': 'Updating...',
        'downloading_updating': 'Downloading and updating...',
        'update_successful': 'Update successful (version {})',
        'update_successful_title': 'Update Successful',
        'update_successful_message': 'App successfully updated to version',
        'restart_question': 'To apply changes, the app needs to restart. Do you want to restart now?',
        'restarting': 'Restarting...',
        'update_error': 'Update error',
        'restart_error': 'Restart error',
        'update': 'Update',
        'dissertation_cover': 'Dissertation\n Cover',
        'notebook_cover': 'Notebook\n or Contract\n Cover',
        'book_cover': 'Book\n Cover',
        'gilded_book_cover': 'Gilded\n Book Cover',
        'theme_guide_title': 'Theme Settings Guide',
        'theme_guide_message': 'Select a color to change all button colors',
        'background_color': 'Background Color',
        'history_guide_title': 'History Page',
        'history_guide_message': 'You can see the last created files here',
        'clear_all': '🧹 Clear All',
        'change_path': '📁 Change Path',
        'empty_history': '📭 History is empty',
        'delete_confirm': 'Are you sure you want to delete this item?',
        'clear_all_confirm': 'Are you sure you want to clear all history?',
        'delete_success': 'Item deleted successfully',
        'clear_all_success': 'History cleared successfully',
        'save_file': 'Save File',
        'file_saved': 'File saved successfully',
        'file_saved_path': 'File saved at:',
        'info_title': 'File Information',
        'file_name': 'File Name',
        'creation_date': 'Creation Date',
        'original_path': 'Original Path',
        'build_info': 'Build Information',
        'title': 'Title',
        'author': 'Author',
        'spine_value_info': 'Spine Value',
        'page_number': 'Page Number',
        'latin_page': 'Latin Page',
        'has': 'Has',
        'does_not_have': 'Does not have',
        'logo_type': 'Logo Type',
        'black_white': 'Black & White',
        'colored': 'Colored',
        'logo_shape': 'Logo Shape',
        'circular': 'Circular',
        'non_circular': 'Non-circular',
        'mm': 'mm',
        'step1': 'Step 1',
        'step2': 'Step 2',
        'step3': 'Step 3',
        'step4': 'Step 4',
        'help_plan_1': 'First step guide',
        'help_plan_2': 'Second step guide',
        'help_plan_3': 'Third step guide',
        'help_plan_4': 'Fourth step guide',
        'spine_value': 'Spine Value (mm):',
        'title_text': 'Title:',
        'author_name': 'Author Name:',
        'date': 'Date:',
        'title_page_number': 'Title Page Number:',
        'output_file_name': 'Output File Name:',
        'select_file': 'Select File',
        'save_location': 'Save Location',
        'no_file_selected': 'No file selected',
        'no_folder_selected': 'No folder selected',
        'no_logo_selected': 'No logo selected',
        'file_selected': 'File selected',
        'folder_selected': 'Folder selected',
        'logo_selected': 'Logo selected',
        'start_making_message': 'Cover making process started...',
        'has_latin_page': 'Dissertation has Latin page',
        'has_latin_page_on': 'Has Latin page',
        'has_latin_page_off': 'No Latin page',
        'logo_black_white': 'Logo is black and white',
        'logo_black_white_on': 'Black and White',
        'logo_black_white_off': 'Colored',
        'logo_circular': 'Logo is circular',
        'logo_circular_on': 'Circular',
        'logo_circular_off': 'Non-circular',
        'refresh': 'Refresh Page',
        'start_making': 'Start Making',
        'load_logo': 'Load Logo',
        'back': '🔙 Back',
        'cancel': 'Cancel',
        'apply': 'Apply',
        'select_year': 'Select Year',
        'select_month': 'Select Month',
        'selected_date': 'Selected Date:',
        'months': ['January', 'February', 'March', 'April', 'May', 'June',
                   'July', 'August', 'September', 'October', 'November', 'December'],
        'pages': ['1 Page', '2 Pages', '3 Pages', '4 Pages', '5 Pages'],
        'welcome_message': '''Welcome to Cover Builder
Click on any cover button to start''',
        'about_us': '''📱 Cover Builder

Developers: Moghiseh & Shaker

📅 Version: {}
📧 Support: support@example.com
📞 Phone: +98-21-12345678

⭐ Designed for creating various covers

❤️ Thank you for choosing us''',
    },
    
    'arabic': {
        'app_title': 'بناء الغلاف',
        'theme_button': '🎨 السمات',
        'history_button': 'التاریخ',
        'guide_button': ' الدلیل',
        'language': 'اللغة',
        "erorr": 'خطأ ',
        'about_button': '📋 معلومات عنا',
        'about_title': 'حول البرنامج',
        'about_message': '''📱 بناء الغلاف

المطورون: مقیسة و شاکر

📅 الإصدار: {}
📧 الدعم: support@example.com
📞 الهاتف: ۹۸۲۱-۱۲۳۴۵۶۷۸+

⭐ تم تصمیم هذا البرنامج لإنشاء أنواع مختلفة من الأغلفة
❤️ شکرًا لاختیارکم لنا''',
        'other_programs': '📦 برامج أخرى',
        'other_programs_title': 'برامجى الأخرى',
        'loading_repos': 'جاري تحميل المعلومات...',
        'github_error': 'خطأ في الاتصال بـ GitHub',
        'no_other_programs': 'لم يتم العثور على برامج أخرى',
        'view_on_github': 'عرض على GitHub',
        'more_info': 'مزيد من المعلومات',
        'refresh': 'تحديث',
        'description': 'الوصف',
        'no_description': 'لا يوجد وصف',
        'unknown': 'غير معروف',
        'language_colon': 'اللغة',
        'stars': 'النجوم',
        'created_at': 'تاريخ الإنشاء',
        'updated_at': 'آخر تحديث',
        'link': 'الرابط',
        'update_title': 'التحقق من التحديثات',
        'current_version_checking': 'الإصدار الحالي: جاري التحقق...',
        'latest_version_checking': 'آخر إصدار: جاري التحقق...',
        'current_version': 'الإصدار الحالي',
        'current_version_unknown': 'الإصدار الحالي: غير معروف',
        'latest_version': 'آخر إصدار',
        'check_update': 'التحقق من التحديثات',
        'check_again': 'تحقق مرة أخرى',
        'start_update': 'بدء التحديث',
        'checking': 'جاري التحقق...',
        'connecting_github': 'جاري الاتصال بـ GitHub...',
        'github_connection_error': 'خطأ في الاتصال بـ GitHub',
        'app_up_to_date': 'برنامجك محدث',
        'new_version_available': 'الإصدار الجديد {} متوفر',
        'new_version_found': 'إصدار جديد',
        'update_question': 'هل تريد التحديث؟',
        'update_note': 'ملاحظة: لن يتم تحديث ملفات .gitignore و README.md.',
        'updating': 'جاري التحديث...',
        'downloading_updating': 'جاري التحميل والتحديث...',
        'update_successful': 'تم التحديث بنجاح (الإصدار {})',
        'update_successful_title': 'تحديث ناجح',
        'update_successful_message': 'تم تحديث البرنامج بنجاح إلى الإصدار',
        'restart_question': 'لتطبيق التغييرات، يجب إعادة تشغيل البرنامج. هل تريد إعادة التشغيل الآن؟',
        'restarting': 'جاري إعادة التشغيل...',
        'update_error': 'خطأ في التحديث',
        'restart_error': 'خطأ في إعادة التشغيل',
        'update': 'تحديث',
        'dissertation_cover': 'بناء غلاف\n الرسالة',
        'notebook_cover': 'بناء غلاف\n دفتر المدرسة أو\n العقود',
        'book_cover': 'بناء غلاف\n الکتب',
        'gilded_book_cover': 'بناء غلاف\n الکتب المذهبة',
        'theme_guide_title': 'دلیل إعدادات السمة',
        'theme_guide_message': 'اختر لونًا لتغییر لون جمیع الأزرار',
        'background_color': 'لون الخلفیة',
        'history_guide_title': 'صفحة التاریخ',
        'history_guide_message': 'یمکنک رؤية آخر الملفات التي تم إنشاؤها هنا',
        'clear_all': '🧹 مسح الكل',
        'change_path': '📁 تغییر المسار',
        'empty_history': '📭 التاریخ فارغ',
        'delete_confirm': 'هل أنت متأكد من حذف هذا العنصر؟',
        'clear_all_confirm': 'هل أنت متأكد من مسح کل التاریخ؟',
        'delete_success': 'تم حذف العنصر بنجاح',
        'clear_all_success': 'تم مسح التاریخ بنجاح',
        'save_file': 'حفظ الملف',
        'file_saved': 'تم حفظ الملف بنجاح',
        'file_saved_path': 'تم حفظ الملف في:',
        'info_title': 'معلومات الملف',
        'file_name': 'اسم الملف',
        'creation_date': 'تاریخ الإنشاء',
        'original_path': 'المسار الأصلي',
        'build_info': 'معلومات البناء',
        'title': 'العنوان',
        'author': 'المؤلف',
        'spine_value_info': 'قیمة العمود الفقري',
        'page_number': 'رقم الصفحة',
        'latin_page': 'الصفحة اللاتینیة',
        'has': 'یوجد',
        'does_not_have': 'لا یوجد',
        'logo_type': 'نوع الشعار',
        'black_white': 'أبیض وأسود',
        'colored': 'ملون',
        'logo_shape': 'شکل الشعار',
        'circular': 'دائري',
        'non_circular': 'غیر دائري',
        'mm': 'ملم',
        'step1': 'الخطوة ۱',
        'step2': 'الخطوة ۲',
        'step3': 'الخطوة ۳',
        'step4': 'الخطوة ۴',
        'help_plan_1': " دليل الخطوة الأولى",
        'help_plan_2': " دليل الخطوة الثانية",
        'help_plan_3': ' دليل الخطوة الثالثة',
        'help_plan_4': ' دليل الخطوة الرابعة',
        'spine_value': 'قیمة العمود الفقري (ملم):',
        'title_text': 'العنوان:',
        'author_name': 'اسم المؤلف:',
        'date': 'التاریخ:',
        'title_page_number': 'رقم صفحة العنوان:',
        'output_file_name': 'اسم ملف الإخراج:',
        'select_file': 'اختر ملف',
        'save_location': 'مکان الحفظ',
        'no_file_selected': 'لم يتم اختیار ملف',
        'no_folder_selected': 'لم يتم اختیار مجلد',
        'no_logo_selected': 'لم يتم اختیار شعار',
        'file_selected': 'تم اختیار الملف',
        'folder_selected': 'تم اختیار المجلد',
        'logo_selected': 'تم اختیار الشعار',
        'start_making_message': 'بدأت عملیة بناء الغلاف...',
        'has_latin_page': 'الرسالة تحتوي على صفحة لاتینیة',
        'has_latin_page_on': 'تحتوي على صفحة لاتینیة',
        'has_latin_page_off': 'لا تحتوي على صفحة لاتینیة',
        'logo_black_white': 'الشعار أبيض وأسود',
        'logo_black_white_on': 'أبیض وأسود',
        'logo_black_white_off': 'ملون',
        'logo_circular': 'الشعار دائري',
        'logo_circular_on': 'دائري',
        'logo_circular_off': 'غیر دائري',
        'refresh': 'تحدیث الصفحة',
        'start_making': 'بدء الإنشاء',
        'load_logo': 'تحمیل الشعار',
        'back': '🔙 رجوع',
        'cancel': 'إلغاء',
        'apply': 'تطبیق',
        'select_year': 'اختر السنة',
        'select_month': 'اختر الشهر',
        'selected_date': 'التاریخ المختار:',
        'months': ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو',
                   'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
        'pages': ['۱ صفحة', '۲ صفحتین', '۳ صفحات', '٤ صفحات', '٥ صفحات'],
        'welcome_message': '''مرحبًا بكم في بناء الغلاف
انقر على أي زر لبدء الإنشاء''',
        'about_us': '''📱 بناء الغلاف

المطورون: مقیسة و شاکر

📅 الإصدار: {}
📧 الدعم: support@example.com
📞 الهاتف: ۹۸۲۱-۱۲۳۴۵۶۷۸+

⭐ تم تصمیم هذا البرنامج لإنشاء أنواع مختلفة من الأغلفة

❤️ شکرًا لاختیارکم لنا''',
    },
    
    'chinese': {
        'app_title': '封面制作器',
        'theme_button': '🎨 主题',
        'history_button': '历史',
        'guide_button': ' 指南',
        'language': '语言',
        "erorr": '错误 ',
        'about_button': '📋 关于我们',
        'about_title': '关于应用程序',
        'about_message': '''📱 封面制作器

开发者: Moghiseh & Shaker

📅 版本: {}
📧 支持: support@example.com
📞 电话: +98-21-12345678

⭐ 专为创建各种封面而设计
❤️ 感谢您选择我们''',
        'other_programs': '📦 其他程序',
        'other_programs_title': '我的其他程序',
        'loading_repos': '正在加载信息...',
        'github_error': '连接到GitHub时出错',
        'no_other_programs': '未找到其他程序',
        'view_on_github': '在GitHub上查看',
        'more_info': '更多信息',
        'refresh': '刷新',
        'description': '描述',
        'no_description': '无描述',
        'unknown': '未知',
        'language_colon': '语言',
        'stars': '星标',
        'created_at': '创建于',
        'updated_at': '更新于',
        'link': '链接',
        'update_title': '检查更新',
        'current_version_checking': '当前版本: 正在检查...',
        'latest_version_checking': '最新版本: 正在检查...',
        'current_version': '当前版本',
        'current_version_unknown': '当前版本: 未知',
        'latest_version': '最新版本',
        'check_update': '检查更新',
        'check_again': '再次检查',
        'start_update': '开始更新',
        'checking': '正在检查...',
        'connecting_github': '正在连接GitHub...',
        'github_connection_error': '连接到GitHub时出错',
        'app_up_to_date': '您的应用程序已是最新',
        'new_version_available': '新版本 {} 可用',
        'new_version_found': '新版本',
        'update_question': '您想要更新吗？',
        'update_note': '注意：.gitignore 和 README.md 文件将不会被更新。',
        'updating': '正在更新...',
        'downloading_updating': '正在下载和更新...',
        'update_successful': '更新成功 (版本 {})',
        'update_successful_title': '更新成功',
        'update_successful_message': '应用程序成功更新到版本',
        'restart_question': '要应用更改，需要重新启动应用程序。您想现在重新启动吗？',
        'restarting': '正在重新启动...',
        'update_error': '更新错误',
        'restart_error': '重新启动错误',
        'update': '更新',
        'dissertation_cover': '论文\n封面',
        'notebook_cover': '笔记本\n或合同\n封面',
        'book_cover': '书籍\n封面',
        'gilded_book_cover': '烫金\n书籍封面',
        'theme_guide_title': '主题设置指南',
        'theme_guide_message': '选择颜色以更改所有按钮颜色',
        'background_color': '背景颜色',
        'history_guide_title': '历史页面',
        'history_guide_message': '您可以在这里查看最近创建的文件',
        'clear_all': '🧹 清除全部',
        'change_path': '📁 更改路径',
        'empty_history': '📭 历史记录为空',
        'delete_confirm': '您确定要删除此项吗？',
        'clear_all_confirm': '您确定要清除所有历史记录吗？',
        'delete_success': '项目删除成功',
        'clear_all_success': '历史记录清除成功',
        'save_file': '保存文件',
        'file_saved': '文件保存成功',
        'file_saved_path': '文件保存在:',
        'info_title': '文件信息',
        'file_name': '文件名',
        'creation_date': '创建日期',
        'original_path': '原始路径',
        'build_info': '构建信息',
        'title': '标题',
        'author': '作者',
        'spine_value_info': '书脊值',
        'page_number': '页数',
        'latin_page': '拉丁页面',
        'has': '有',
        'does_not_have': '没有',
        'logo_type': '徽标类型',
        'black_white': '黑白',
        'colored': '彩色',
        'logo_shape': '徽标形状',
        'circular': '圆形',
        'non_circular': '非圆形',
        'mm': '毫米',
        'step1': '步骤 1',
        'step2': '步骤 2',
        'step3': '步骤 3',
        'step4': '步骤 4',
        'help_plan_1': '第一步指南',
        'help_plan_2': '第二步指南',
        'help_plan_3': '第三步指南',
        'help_plan_4': '第四步指南',
        'spine_value': '书脊值 (毫米):',
        'title_text': '标题:',
        'author_name': '作者姓名:',
        'date': '日期:',
        'title_page_number': '标题页数:',
        'output_file_name': '输出文件名:',
        'select_file': '选择文件',
        'save_location': '保存位置',
        'no_file_selected': '未选择文件',
        'no_folder_selected': '未选择文件夹',
        'no_logo_selected': '未选择徽标',
        'file_selected': '已选择文件',
        'folder_selected': '已选择文件夹',
        'logo_selected': '已选择徽标',
        'start_making_message': '封面制作过程开始...',
        'has_latin_page': '论文有拉丁页面',
        'has_latin_page_on': '有拉丁页面',
        'has_latin_page_off': '无拉丁页面',
        'logo_black_white': '徽标是黑白的',
        'logo_black_white_on': '黑白',
        'logo_black_white_off': '彩色',
        'logo_circular': '徽标是圆形的',
        'logo_circular_on': '圆形',
        'logo_circular_off': '非圆形',
        'refresh': '刷新页面',
        'start_making': '开始制作',
        'load_logo': '加载徽标',
        'back': '🔙 返回',
        'cancel': '取消',
        'apply': '应用',
        'select_year': '选择年份',
        'select_month': '选择月份',
        'selected_date': '选择的日期:',
        'months': ['一月', '二月', '三月', '四月', '五月', '六月',
                   '七月', '八月', '九月', '十月', '十一月', '十二月'],
        'pages': ['1 页', '2 页', '3 页', '4 页', '5 页'],
        'welcome_message': '''欢迎使用封面制作器
点击任何封面按钮开始''',
        'about_us': '''📱 封面制作器

开发者: Moghiseh & Shaker

📅 版本: {}
📧 支持: support@example.com
📞 电话: +98-21-12345678

⭐ 专为创建各种封面而设计

❤️ 感谢您选择我们''',
    },
    
    'russian': {
        'app_title': 'Создатель обложек',
        'theme_button': '🎨 Темы',
        'history_button': 'История',
        'guide_button': ' Руководство',
        'language': 'Язык',
        "erorr": 'Ошибка',
        'about_button': '📋 О нас',
        'about_title': 'О приложении',
        'about_message': '''📱 Создатель обложек

Разработчики: Moghiseh & Shaker

📅 Версия: {}
📧 Поддержка: support@example.com
📞 Телефон: +98-21-12345678

⭐ Разработано для создания различных обложек
❤️ Спасибо, что выбрали нас''',
        'other_programs': '📦 Другие программы',
        'other_programs_title': 'Мои другие программы',
        'loading_repos': 'Загрузка информации...',
        'github_error': 'Ошибка подключения к GitHub',
        'no_other_programs': 'Другие программы не найдены',
        'view_on_github': 'Смотреть на GitHub',
        'more_info': 'Подробнее',
        'refresh': 'Обновить',
        'description': 'Описание',
        'no_description': 'Нет описания',
        'unknown': 'Неизвестно',
        'language_colon': 'Язык',
        'stars': 'Звезды',
        'created_at': 'Создано',
        'updated_at': 'Обновлено',
        'link': 'Ссылка',
        'update_title': 'Проверка обновлений',
        'current_version_checking': 'Текущая версия: Проверка...',
        'latest_version_checking': 'Последняя версия: Проверка...',
        'current_version': 'Текущая версия',
        'current_version_unknown': 'Текущая версия: Неизвестно',
        'latest_version': 'Последняя версия',
        'check_update': 'Проверить обновления',
        'check_again': 'Проверить снова',
        'start_update': 'Начать обновление',
        'checking': 'Проверка...',
        'connecting_github': 'Подключение к GitHub...',
        'github_connection_error': 'Ошибка подключения к GitHub',
        'app_up_to_date': 'Ваше приложение обновлено',
        'new_version_available': 'Доступна новая версия {}',
        'new_version_found': 'Новая версия',
        'update_question': 'Хотите обновить?',
        'update_note': 'Примечание: файлы .gitignore и README.md не будут обновлены.',
        'updating': 'Обновление...',
        'downloading_updating': 'Загрузка и обновление...',
        'update_successful': 'Обновление успешно (версия {})',
        'update_successful_title': 'Обновление успешно',
        'update_successful_message': 'Приложение успешно обновлено до версии',
        'restart_question': 'Для применения изменений необходимо перезапустить приложение. Хотите перезапустить сейчас?',
        'restarting': 'Перезапуск...',
        'update_error': 'Ошибка обновления',
        'restart_error': 'Ошибка перезапуска',
        'update': 'Обновление',
        'dissertation_cover': 'Диссертация\n Обложка',
        'notebook_cover': 'Тетрадь\n или Договор\n Обложка',
        'book_cover': 'Книга\n Обложка',
        'gilded_book_cover': 'Позолоченная\n Обложка книги',
        'theme_guide_title': 'Руководство по настройке темы',
        'theme_guide_message': 'Выберите цвет, чтобы изменить цвет всех кнопок',
        'background_color': 'Цвет фона',
        'history_guide_title': 'Страница истории',
        'history_guide_message': 'Здесь вы можете увидеть последние созданные файлы',
        'clear_all': '🧹 Очистить все',
        'change_path': '📁 Изменить путь',
        'empty_history': '📭 История пуста',
        'delete_confirm': 'Вы уверены, что хотите удалить этот элемент?',
        'clear_all_confirm': 'Вы уверены, что хотите очистить всю историю?',
        'delete_success': 'Элемент успешно удален',
        'clear_all_success': 'История успешно очищена',
        'save_file': 'Сохранить файл',
        'file_saved': 'Файл успешно сохранен',
        'file_saved_path': 'Файл сохранен в:',
        'info_title': 'Информация о файле',
        'file_name': 'Имя файла',
        'creation_date': 'Дата создания',
        'original_path': 'Исходный путь',
        'build_info': 'Информация о создании',
        'title': 'Название',
        'author': 'Автор',
        'spine_value_info': 'Значение корешка',
        'page_number': 'Номер страницы',
        'latin_page': 'Латинская страница',
        'has': 'Есть',
        'does_not_have': 'Нет',
        'logo_type': 'Тип логотипа',
        'black_white': 'Черно-белый',
        'colored': 'Цветной',
        'logo_shape': 'Форма логотипа',
        'circular': 'Круглый',
        'non_circular': 'Некруглый',
        'mm': 'мм',
        'step1': 'Шаг 1',
        'step2': 'Шаг 2',
        'step3': 'Шаг 3',
        'step4': 'Шаг 4',
        'help_plan_1': 'Руководство по первому шагу',
        'help_plan_2': 'Руководство по второму шагу',
        'help_plan_3': 'Руководство по третьему шагу',
        'help_plan_4': 'Руководство по четвертому шагу',
        'spine_value': 'Значение корешка (мм):',
        'title_text': 'Название:',
        'author_name': 'Имя автора:',
        'date': 'Дата:',
        'title_page_number': 'Номер титульной страницы:',
        'output_file_name': 'Имя выходного файла:',
        'select_file': 'Выбрать файл',
        'save_location': 'Место сохранения',
        'no_file_selected': 'Файл не выбран',
        'no_folder_selected': 'Папка не выбрана',
        'no_logo_selected': 'Логотип не выбран',
        'file_selected': 'Файл выбран',
        'folder_selected': 'Папка выбрана',
        'logo_selected': 'Логотип выбран',
        'start_making_message': 'Процесс создания обложки начат...',
        'has_latin_page': 'Диссертация имеет латинскую страницу',
        'has_latin_page_on': 'Имеет латинскую страницу',
        'has_latin_page_off': 'Без латинской страницы',
        'logo_black_white': 'Логотип черно-белый',
        'logo_black_white_on': 'Черно-белый',
        'logo_black_white_off': 'Цветной',
        'logo_circular': 'Логотип круглый',
        'logo_circular_on': 'Круглый',
        'logo_circular_off': 'Некруглый',
        'refresh': 'Обновить страницу',
        'start_making': 'Начать создание',
        'load_logo': 'Загрузить логотип',
        'back': '🔙 Назад',
        'cancel': 'Отмена',
        'apply': 'Применить',
        'select_year': 'Выберите год',
        'select_month': 'Выберите месяц',
        'selected_date': 'Выбранная дата:',
        'months': ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
                   'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
        'pages': ['1 страница', '2 страницы', '3 страницы', '4 страницы', '5 страниц'],
        'welcome_message': '''Добро пожаловать в Создатель обложек
Нажмите любую кнопку обложки, чтобы начать''',
        'about_us': '''📱 Создатель обложек

Разработчики: Moghiseh & Shaker

📅 Версия: {}
📧 Поддержка: support@example.com
📞 Телефон: +98-21-12345678

⭐ Разработано для создания различных обложек

❤️ Спасибо, что выбрали нас''',
    },
    
    'spanish': {
        'app_title': 'Creador de Portadas',
        'theme_button': '🎨 Temas',
        'history_button': 'Historial',
        'guide_button': ' Guía',
        'language': 'Idioma',
        "erorr": 'Error',
        'about_button': '📋 Acerca de',
        'about_title': 'Acerca de la aplicación',
        'about_message': '''📱 Creador de Portadas

Desarrolladores: Moghiseh & Shaker

📅 Versión: {}
📧 Soporte: support@example.com
📞 Teléfono: +98-21-12345678

⭐ Diseñado para crear varios tipos de portadas
❤️ Gracias por elegirnos''',
        'other_programs': '📦 Otros Programas',
        'other_programs_title': 'Mis Otros Programas',
        'loading_repos': 'Cargando información...',
        'github_error': 'Error al conectar con GitHub',
        'no_other_programs': 'No se encontraron otros programas',
        'view_on_github': 'Ver en GitHub',
        'more_info': 'Más información',
        'refresh': 'Actualizar',
        'description': 'Descripción',
        'no_description': 'Sin descripción',
        'unknown': 'Desconocido',
        'language_colon': 'Idioma',
        'stars': 'Estrellas',
        'created_at': 'Creado el',
        'updated_at': 'Actualizado el',
        'link': 'Enlace',
        'update_title': 'Buscar actualizaciones',
        'current_version_checking': 'Versión actual: Comprobando...',
        'latest_version_checking': 'Última versión: Comprobando...',
        'current_version': 'Versión actual',
        'current_version_unknown': 'Versión actual: Desconocida',
        'latest_version': 'Última versión',
        'check_update': 'Buscar actualizaciones',
        'check_again': 'Comprobar de nuevo',
        'start_update': 'Iniciar actualización',
        'checking': 'Comprobando...',
        'connecting_github': 'Conectando a GitHub...',
        'github_connection_error': 'Error al conectar con GitHub',
        'app_up_to_date': 'Tu aplicación está actualizada',
        'new_version_available': 'Nueva versión {} disponible',
        'new_version_found': 'Nueva versión',
        'update_question': '¿Quieres actualizar?',
        'update_note': 'Nota: Los archivos .gitignore y README.md no se actualizarán.',
        'updating': 'Actualizando...',
        'downloading_updating': 'Descargando y actualizando...',
        'update_successful': 'Actualización exitosa (versión {})',
        'update_successful_title': 'Actualización exitosa',
        'update_successful_message': 'Aplicación actualizada exitosamente a la versión',
        'restart_question': 'Para aplicar los cambios, la aplicación debe reiniciarse. ¿Quieres reiniciar ahora?',
        'restarting': 'Reiniciando...',
        'update_error': 'Error de actualización',
        'restart_error': 'Error al reiniciar',
        'update': 'Actualización',
        'dissertation_cover': 'Portada de\n Tesis',
        'notebook_cover': 'Portada de\n Cuaderno o\n Contrato',
        'book_cover': 'Portada de\n Libro',
        'gilded_book_cover': 'Portada de\n Libro Dorado',
        'theme_guide_title': 'Guía de configuración de temas',
        'theme_guide_message': 'Seleccione un color para cambiar el color de todos los botones',
        'background_color': 'Color de fondo',
        'history_guide_title': 'Página de historial',
        'history_guide_message': 'Aquí puede ver los últimos archivos creados',
        'clear_all': '🧹 Limpiar todo',
        'change_path': '📁 Cambiar ruta',
        'empty_history': '📭 El historial está vacío',
        'delete_confirm': '¿Estás seguro de que quieres eliminar este elemento?',
        'clear_all_confirm': '¿Estás seguro de que quieres limpiar todo el historial?',
        'delete_success': 'Elemento eliminado con éxito',
        'clear_all_success': 'Historial limpiado con éxito',
        'save_file': 'Guardar archivo',
        'file_saved': 'Archivo guardado con éxito',
        'file_saved_path': 'Archivo guardado en:',
        'info_title': 'Información del archivo',
        'file_name': 'Nombre del archivo',
        'creation_date': 'Fecha de creación',
        'original_path': 'Ruta original',
        'build_info': 'Información de creación',
        'title': 'Título',
        'author': 'Autor',
        'spine_value_info': 'Valor del lomo',
        'page_number': 'Número de página',
        'latin_page': 'Página latina',
        'has': 'Tiene',
        'does_not_have': 'No tiene',
        'logo_type': 'Tipo de logotipo',
        'black_white': 'Blanco y negro',
        'colored': 'Color',
        'logo_shape': 'Forma del logotipo',
        'circular': 'Circular',
        'non_circular': 'No circular',
        'mm': 'mm',
        'step1': 'Paso 1',
        'step2': 'Paso 2',
        'step3': 'Paso 3',
        'step4': 'Paso 4',
        'help_plan_1': 'Guía del primer paso',
        'help_plan_2': 'Guía del segundo paso',
        'help_plan_3': 'Guía del tercer paso',
        'help_plan_4': 'Guía del cuarto paso',
        'spine_value': 'Valor del lomo (mm):',
        'title_text': 'Título:',
        'author_name': 'Nombre del autor:',
        'date': 'Fecha:',
        'title_page_number': 'Número de página de título:',
        'output_file_name': 'Nombre del archivo de salida:',
        'select_file': 'Seleccionar archivo',
        'save_location': 'Ubicación de guardado',
        'no_file_selected': 'Ningún archivo seleccionado',
        'no_folder_selected': 'Ninguna carpeta seleccionada',
        'no_logo_selected': 'Ningún logotipo seleccionado',
        'file_selected': 'Archivo seleccionado',
        'folder_selected': 'Carpeta seleccionada',
        'logo_selected': 'Logotipo seleccionado',
        'start_making_message': 'Proceso de creación de portada iniciado...',
        'has_latin_page': 'La tesis tiene página latina',
        'has_latin_page_on': 'Tiene página latina',
        'has_latin_page_off': 'Sin página latina',
        'logo_black_white': 'El logotipo es blanco y negro',
        'logo_black_white_on': 'Blanco y negro',
        'logo_black_white_off': 'Color',
        'logo_circular': 'El logotipo es circular',
        'logo_circular_on': 'Circular',
        'logo_circular_off': 'No circular',
        'refresh': 'Actualizar página',
        'start_making': 'Comenzar creación',
        'load_logo': 'Cargar logotipo',
        'back': '🔙 Atrás',
        'cancel': 'Cancelar',
        'apply': 'Aplicar',
        'select_year': 'Seleccionar año',
        'select_month': 'Seleccionar mes',
        'selected_date': 'Fecha seleccionada:',
        'months': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                   'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        'pages': ['1 página', '2 páginas', '3 páginas', '4 páginas', '5 páginas'],
        'welcome_message': '''Bienvenido a Creador de Portadas
Haga clic en cualquier botón de portada para comenzar''',
        'about_us': '''📱 Creador de Portadas

Desarrolladores: Moghiseh & Shaker

📅 Versión: {}
📧 Soporte: support@example.com
📞 Teléfono: +98-21-12345678

⭐ Diseñado para crear varios tipos de portadas

❤️ Gracias por elegirnos''',
    }
}

# زبان پیش‌فرض
current_language = 'persian'

def get_text(key):
    """دریافت متن بر اساس کلید و زبان فعلی"""
    try:
        return languages[current_language][key]
    except KeyError:
        try:
            return languages['persian'][key]
        except:
            return key

def set_language(lang):
    """تغییر زبان برنامه"""
    global current_language
    if lang in languages:
        current_language = lang
        return True
    return False

def get_months():
    """دریافت لیست ماه‌ها بر اساس زبان فعلی"""
    return languages[current_language]['months']

def get_pages():
    """دریافت لیست صفحات بر اساس زبان فعلی"""
    return languages[current_language]['pages']

def get_language_name(lang_code):
    """دریافت نام زبان به زبان خودش"""
    language_names = {
        'persian': 'فارسی',
        'english': 'English',
        'arabic': 'العربية',
        'chinese': '中文',
        'russian': 'Русский',
        'spanish': 'Español'
    }
    return language_names.get(lang_code, lang_code)

def get_boolean_text(value):
    """دریافت متن بولین بر اساس زبان"""
    if value in [True, 'on', 'has_latin_page_on', 'logo_black_white_on', 'logo_circular_on']:
        return get_text('has')
    else:
        return get_text('does_not_have')